### ISSUE TITLE
c++ linkage

### ISSUE THREAD

**Issue by patryk-belka-wizzdev** [joelguittet/mender-mcu-client#5]
Would it be possible to add an extern C linkage for applications written in C++? That's a common thing for esp32 libraries to add to each header file at the beginning: 
```
#ifdef __cplusplus
extern "C" {
#endif
```
and at the end:
```
#ifdef __cplusplus
}
#endif
```

**Comment by joelguittet** [comment]
Of course! Don't know how it's possible I forgot to add this. It's now done, available on master branch following https://github.com/joelguittet/mender-mcu-client/pull/6.
