### ISSUE TITLE
Error ESP_ERR_NVS_INVALID_HANDLE when new deployment is downloaded with mender-mcu-client

### ISSUE THREAD

**Issue by mbcsa** [joelguittet/mender-mcu-client#87]
Files

- mender-mcu-client/mender-mcu-client/platform/storage/esp-idf/nvs/src/mender-storage.c (Line 29)

- mender-mcu-client/mender-mcu-client/platform/storage/posix/src/mender-storage.c (Line 36)

specifies

`#define MENDER_STORAGE_NVS_DEPLOYMENT_DATA "deployment-data.json"`

Then, in line 135,

`if (ESP_OK != nvs_set_str(mender_storage_nvs_handle, MENDER_STORAGE_NVS_DEPLOYMENT_DATA, deployment_data)) {`

when "nvs_set_str" takes place, returns ESP_ERR_NVS_INVALID_HANDLE error.

As results, the firmware updates himself, but it is not restarted.

After manually restart, we can notice that has been upgraded.

According to documentation, max length for keys is 15 chars.

![image](https://github.com/user-attachments/assets/e89c1f23-e22b-4e82-842a-ede1e0d56d86)

Confirmed that changing to

`#define MENDER_STORAGE_NVS_DEPLOYMENT_DATA "deployment.json"`

results in successful upgrade.

**Comment by joelguittet** [comment]
Hello @mbcsa 

Thanks for reporting this error and for the detailed analysis! I will do a hotfix right now.

The filename was changed at https://github.com/joelguittet/mender-mcu-client/commit/9b375e6429a31c7acb5bca7294ca479d02dac037 but it seems I haven't seen this at this time. Sorry for the inconvenience.

Joel

**Comment by joelguittet** [comment]
@mbcsa 

I have created a hotfix release 0.11.1 to fix this issue, and also update the mender-esp32-example.
I have tested and looks fine for me, I let you confirm if this is okay for you as well and we can close this issue after that
